### ISSUE TITLE
Can we have clarification regarding what "Defensive" means?

### ISSUE THREAD

**Issue by jrconlin** [twitter/innovators-patent-agreement#15]
I'm having trouble determining what might cause a "Defensive" action. 

For instance, say I create a library that uses GPL. I discover that a IPA holder uses it, but fails to publish the code/include copyright statement/etc. If I sought correction, would that trigger a "Defensive" action of being sued for any patent related content my library (or other libraries I may have authored) may contain?

The above is just one potential non-patent related scenario that could trigger the defense mechanism. I can easily imagine others.

**Comment by JaredCrawford** [comment]
If the term "intellectual property lawsuit" in 2(a) was replaced with "patent infringement lawsuit," would your concern be alleviated? If so, I believe this is a duplicate of #1 (that is being considered by @benltwitter).

**Comment by jrconlin** [comment]
Yes, I believe it would address most of the concerns.

Closing the issue as a duplicate.
