### ISSUE TITLE
Public Disclosure of License

### ISSUE THREAD

**Issue by JaredCrawford** [twitter/innovators-patent-agreement#16]
Most current patent licensing agreements are never published (either due to lack of public interest or non-disclosure agreements). However, many of the IPA's benefits are only realized if there is public disclosure, including a competitor's incentive to avoid triggering the section 2 clauses.

In the case of Twitter's patents, we have that confirmation. In the [blog post](http://engineering.twitter.com/2012/04/introducing-innovators-patent-agreement.html) announcing IPA, Twitter said that all of their patents "past and present" would be licensed under IPA. This leaves an obvious question about Twitter's future patents or patents by other companies utilizing IPA. 

So my question is, what is the best way to inform the public that a patent is IPA-licensed? For those unfamiliar with patent assignment, the USPTO does maintain an assignment database, but it is fairly cursory and probably not well-suited for this task. ([example](http://assignments.uspto.gov/assignments/q?db=pat&pub=20100199180)) 

Does there need to be an IPA database to publish copies of signed documents? Is this GitHub repository well suited for that database? If not, should there be a centralized or per-company database? Thoughts?

**Comment by infogulch** [comment]
No, GitHub would probably not be suited for such a database, at least in the long term. (Though it might be convenient in the short term.)

Does the IPA itself even require that its existence be declared publicly? (If not, this may be a good addition)

**Comment by benltwitter** [comment]
Just a clarification.  Current patent assignments are, in fact, publicly disclosed.  They are recorded in the patent office.  They are not conveniently accessible (just like real property assignments, you have to go down to the patent office and look at dead trees), but they are publicly accessible.  That's one of the reasons we chose to do it this way.

It would be a good thing if someone would turn these records into a form that could be accessible through the Internet.

**Comment by JaredCrawford** [comment]
Interesting, it appears I was misinformed. I'll close this issue as misleading, but I still think greater public access to this information, in a digital format that an engineer can easily reach, helps serve IPAs purpose.
