### ISSUE TITLE
Clarify attribution requirement

### ISSUE THREAD

**Issue by jboehmig** [twitter/innovators-patent-agreement#26]
The CC Attribution 3.0 Unported license requires that the end-user "must attribute the work in the manner specified by the author or licensor," but I don't see the attribution requirement specified anywhere in the current version.

**Comment by caniszczyk** [comment]
A simple text in the README should suffice:
"Innovators Patent Agreement" © 2012 Twitter, Inc, used under a Creative Commons Attribution Unported license: http://creativecommons.org/licenses/by/3.0/

I added the README: 
https://github.com/twitter/innovators-patent-agreement#license

**Comment by jboehmig** [comment]
That does it!  Thanks for taking a look.
