### ISSUE TITLE
What happens upon the death of inventor?

### ISSUE THREAD

**Issue by nehresma** [twitter/innovators-patent-agreement#3]
"If Assignee needs to assert any of the Patent claims against any entity for other than a Defensive Purpose, Assignees must obtain prior written permission from all of the Inventors without additional consideration or threat."

If the inventor is no longer around, does the company then have the ability to use this for offensive (not just defensive) tactics?  If that's the case, the paranoid among us may think that for a high value patent this gives the company incentive to see to it that the inventor is no longer breathing.  :)

**Comment by amirmc** [comment]
Does the last sentence in Para 4 answer this? (must admit that I don't understand much of that para though)

> _"This license to the Inventors is not assignable but may pass to the heirs of an inventor in the case that the inventor is deceased."_

**Comment by nehresma** [comment]
Indeed it does -- I missed it.  Thanks.
