### ISSUE TITLE
Resale of patent rights is neither forbidden nor protected

### ISSUE THREAD

**Issue by jamesarosen** [twitter/innovators-patent-agreement#5]
The Company could easily create an unrelated shell company, sell the patent rights for $1, and have that company use the patent offensively. Offering the Inventors right-of-refusal on sale of this right would prevent that.

Additionally, the Company could sell the patent rights (along with the rest of the company or alone) for a large sum. The Inventors would probably not have the means to execute their right-of-refusal, so a separate clause granting them 50% of the sale price (of the patent rights alone, or itemized if bundled) would disincentivize such a sale.

**Comment by mdekstrand** [comment]
The pledge to only engage in defensive use of the patents is a permanent encumbrance that follows the patent for its life. Part of the pledge is that, if the patent is ever sold, the terms of sale will require that the pledge continue to be honored. So they can't create a shell company to use the patent offensively - the shell company would be bound by the same obligations as the original employer.

**Comment by jamesarosen** [comment]
Courts are generally unwilling to uphold perpetual contracts. It's true that this contract's life is limited, but only by the life of the patent itself, which is currently a specific term of years, but is not guaranteed to be. (Congress can always amend the patent laws.) This may be enough to bind subsequent holders to the contract, but it may not.

_Later_: IANAL. Is my take on the likelihood of Transferees being bound by this contract at all reasonable?

**Comment by JaredCrawford** [comment]
The terms of patents are guaranteed to be for a limited time. Congress can modify the term, but cannot make a patent perpetual.

"The Congress shall have power … to promote the Progress of Science and useful Arts, by securing **for limited Times** to Authors and Inventors the exclusive Right to their respective Writings and Discoveries;"
- Article I, Section 8, Clause 8 of the United States Constitution

**Comment by jamesarosen** [comment]
Well played!

**Comment by jdunck** [comment]
@JaredCrawford Unfortunately we have seen that doesn't hold much practical weight in the case of copyright - originally for 14 + a single 14-year extension.  Now, we have practically perpetual copyright:
http://en.wikipedia.org/wiki/Copyright_Term_Extension_Act

**Comment by Chuckv** [comment]
agreed regarding copyright (I expect lobbyists for the mouse to see to it that (c) will be extended any time steamboat willy is in danger of going public domain)   However we have not seen that sort of movement for Patents, nor I think can logical arguments be made for it, especially given time to market is faster these days than when patent law originated.

**Comment by JaredCrawford** [comment]
Your point is well taken, but the practical effects are not in issue here. 

To summarize, a court would not void or disfavor a contract simply because it is perpetual if it is bounded by the term of a patent that is constitutionally non-perpetual.

**Comment by jdunck** [comment]
I concede the point. :)
